@startwbs Connections Temperature Controller
!theme plain

* Temperature Controller
** GPIO
*** Activate Heater
*** Enable
** AnalogIn
*** Temperature
** Serial
*** ModuleCom
@endwbs

@startwbs Connections PiL Simulator
!theme plain

* PiL Simulator
** GPIO
*** Activate Heater
*** Enable
** AnalogOut
*** Temperature
** Serial
*** ModuleCom
@endwbs
